security:
  jwt:
    url: /auth/
    header: Authorization
    prefix: 'Bearer '
    expiration: 3600
    secret: <my-secret>
  service:
    username: <service-account>
    password: <service-password>
    role: SERVICE