security:
  jwt:
    url: /auth/
    header: Authorization
    prefix: 'Bearer '
    expiration: 3600
    secret: <my-secret>
  service:
    username: <service-account>
    password: <service-password>
    role: SERVICE

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: <db-account>
      password: <db-password>